"""
Pre-configured Pakistani news sources.

These are loaded into the ``news_sources`` table on first run or via
a seed script.  Each entry maps directly to a NewsSource row.

Selectors last verified: 2026-05-06 against live HTML.
"""

from __future__ import annotations

PAKISTANI_NEWS_SOURCES: list[dict] = [
    # ── HTTPX-only sources (no browser needed) ─────────────
    {
        "name": "Express Tribune",
        "base_url": "https://tribune.com.pk",
        "region": "National",
        "country": "Pakistan",
        "language": "en",
        "scrape_config": {
            "list_url": "https://tribune.com.pk/latest",
            "article_selector": "div.horiz-news3-caption",
            "link_selector": "div.horiz-news3-caption a",
            "title_selector": "h1",
            "content_selector": "div.story-content",
            "date_selector": "span.date",
            "date_format": "%B %d, %Y",
            "use_playwright": False,
        },
        "schedule": "0 */4 * * *",
    },
    {
        "name": "ARY News",
        "base_url": "https://arynews.tv",
        "region": "National",
        "country": "Pakistan",
        "language": "en",
        "scrape_config": {
            "list_url": "https://arynews.tv/en/latest-news/",
            "article_selector": "div.post-info",
            "link_selector": "h2 a, h3 a",
            "title_selector": "h1",
            "content_selector": "div.post__content",
            "date_selector": "time",
            "date_format": "%Y-%m-%dT%H:%M:%S%z",
            "use_playwright": False,
        },
        "schedule": "0 */4 * * *",
    },
    {
        "name": "The Nation",
        "base_url": "https://www.nation.com.pk",
        "region": "National",
        "country": "Pakistan",
        "language": "en",
        "scrape_config": {
            "list_url": "https://www.nation.com.pk/latest",
            "article_selector": "h3.jeg_post_title",
            "link_selector": "h3.jeg_post_title a",
            "title_selector": "h1.jeg_post_title",
            "content_selector": "div.content-inner",
            "date_selector": "div.jeg_meta_date",
            "date_format": "%B %d, %Y",
            "use_playwright": False,
        },
        "schedule": "0 */4 * * *",
    },
    {
        "name": "Pakistan Today",
        "base_url": "https://www.pakistantoday.com.pk",
        "region": "National",
        "country": "Pakistan",
        "language": "en",
        "scrape_config": {
            "list_url": "https://www.pakistantoday.com.pk/category/national/",
            "article_selector": "div",
            "link_selector": "div a",
            "title_selector": "h1",
            "content_selector": "div.post-content",
            "date_selector": "time",
            "date_format": "%B %d, %Y",
            "use_playwright": False,
        },
        "schedule": "0 */6 * * *",
    },
    {
        "name": "Daily Pakistan",
        "base_url": "https://en.dailypakistan.com.pk",
        "region": "National",
        "country": "Pakistan",
        "language": "en",
        "scrape_config": {
            "list_url": "https://en.dailypakistan.com.pk/latest-news",
            "article_selector": "li",
            "link_selector": "li a",
            "title_selector": "h1",
            "content_selector": "div.brxe-post-content",
            "date_selector": "time",
            "date_format": "%B %d, %Y",
            "use_playwright": False,
        },
        "schedule": "0 */6 * * *",
    },
    # ── Playwright-required sources (bot protection / JS) ──
    {
        "name": "Dawn News",
        "base_url": "https://www.dawn.com",
        "region": "National",
        "country": "Pakistan",
        "language": "en",
        "scrape_config": {
            "list_url": "https://www.dawn.com/latest-news",
            "article_selector": "article.story",
            "link_selector": "h2.story__title a",
            "title_selector": "h2.story__title",
            "content_selector": "div.story__content",
            "date_selector": "span.timestamp--time",
            "date_format": "%Y-%m-%dT%H:%M:%S%z",
            "use_playwright": True,
        },
        "schedule": "0 */4 * * *",
    },
    {
        "name": "The News International",
        "base_url": "https://www.thenews.com.pk",
        "region": "National",
        "country": "Pakistan",
        "language": "en",
        "scrape_config": {
            "list_url": "https://www.thenews.com.pk/latest",
            "article_selector": "div.widget__headline",
            "link_selector": "h2 a",
            "title_selector": "h1",
            "content_selector": "div.story-detail",
            "date_selector": "span.date",
            "date_format": "%B %d, %Y",
            "use_playwright": True,
        },
        "schedule": "0 */4 * * *",
    },
    {
        "name": "Geo News Urdu",
        "base_url": "https://www.geo.tv",
        "region": "National",
        "country": "Pakistan",
        "language": "ur",
        "scrape_config": {
            "list_url": "https://www.geo.tv/urdu",
            "article_selector": "div.entry",
            "link_selector": "h2 a",
            "title_selector": "h1.title",
            "content_selector": "div.content-area",
            "date_selector": "span.date",
            "date_format": "%d %b, %Y",
            "use_playwright": True,
        },
        "schedule": "0 */6 * * *",
    },
    {
        "name": "Dunya News",
        "base_url": "https://dunyanews.tv",
        "region": "National",
        "country": "Pakistan",
        "language": "ur",
        "scrape_config": {
            "list_url": "https://dunyanews.tv/urdu",
            "article_selector": "div.news-box",
            "link_selector": "h3 a",
            "title_selector": "h1.title",
            "content_selector": "div.content-detail",
            "date_selector": "span.date",
            "date_format": "%d %b %Y",
            "use_playwright": True,
        },
        "schedule": "0 */6 * * *",
    },
]
