steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/bimari-haunter:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bimari-haunter:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy bimari-haunter \
        --image gcr.io/$PROJECT_ID/bimari-haunter:$SHORT_SHA \
        --region $REGION \
        --platform managed \
        --memory 4Gi \
        --cpu 2 \
        --allow-unauthenticated
images:
- 'gcr.io/$PROJECT_ID/bimari-haunter:$SHORT_SHA'
options:
  substitutionOption: 'ALLOW_LOOSE'
timeout: '3600s'